x-common-healthcheck: &default-healthcheck
  interval: 5s
  timeout: 5s
  retries: 12

services:
  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:29092"  # Map host 9092 to container 29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: CONTAINER_INTERNAL://${KAFKA_BOOTSTRAP_SERVERS},HOST://0.0.0.0:29092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: CONTAINER_INTERNAL://${KAFKA_BOOTSTRAP_SERVERS},HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTAINER_INTERNAL:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: CONTAINER_INTERNAL
      KAFKA_PROCESS_ROLES: broker,controller
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      # Auto-create __consumer_offsets
    healthcheck:
      test: nc -z kafka ${KAFKA_PORT} || exit 1
      <<: *default-healthcheck

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      kafka:
        condition: service_healthy
